$sources: !pw.io.fs.read
  path: data/incoming
  format: binary
  with_metadata: true
  mode: streaming

$llm: !pw.xpacks.llm.llms.LiteLLMChat
  model: "anthropic/claude-3-5-sonnet-20241022"
  api_key: $ANTHROPIC_API_KEY
  retry_strategy: !pw.udfs.ExponentialBackoffRetryStrategy
    max_retries: 6
  cache_strategy: !pw.udfs.DefaultCache {}
  temperature: 0
  capacity: 8

$embedder: !pw.xpacks.llm.embedders.SentenceTransformerEmbedder
  model: "all-MiniLM-L12-v2"

$splitter: !pw.xpacks.llm.splitters.TokenCountSplitter
  max_tokens: 800
  min_tokens: 200

$parser: !src.parsers.landingai_parser.LandingAIRadiologyParser
  api_key: $LANDINGAI_API_KEY
  capacity: 4
  results_dir: "data/extraction_results"
  cache_strategy: !pw.udfs.DefaultCache {}
  async_mode: "fully_async"
  

$retriever_factory: !pw.stdlib.indexing.BruteForceKnnFactory
  reserved_space: 1000
  embedder: $embedder
  metric: !pw.stdlib.indexing.BruteForceKnnMetricKind.COS

$document_store: !src.store.RadiologyDocumentStore.RadiologyDocumentStore
  docs: $sources
  retriever_factory: $retriever_factory
  splitter: $splitter
  parser: $parser

question_answerer: !src.intelligence.critical_alert_answerer.RadiologyQuestionAnswerer
  llm: $llm
  indexer: $document_store
  search_topk: 6

mcp_server: !pw.xpacks.llm.mcp_server.PathwayMcp
  name: "Document Processing MCP Server"
  transport: "streamable-http"
  host: "localhost"
  port: $MCP_PORT
  serve:
    - $document_store

host: "0.0.0.0"
port: $REST_PORT

with_cache: true

terminate_on_error: false

# cache_backend: !pw.persistence.Backend.filesystem
#   path: "data/cache"
